export const STOCK_PROFILE_BASES = {
  ALP: {
    legalName: "Alpha Neural Holdings",
    countryCode: "US",
    exchange: "NASDAQ",
    foundedYear: 2011,
    listedDate: "2018-06-14",
    ceo: "Mina Hart",
    website: "https://www.alpha-neural.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "foundationModelLicensing", value: 44, color: "#4d8cff" },
      { id: "inferenceCloud", value: 31, color: "#22c37a" },
      { id: "enterpriseCopilot", value: 25, color: "#45c6ff" },
    ],
  },
  SYN: {
    legalName: "Synapse Cloud Systems",
    countryCode: "US",
    exchange: "NASDAQ",
    foundedYear: 2013,
    listedDate: "2019-09-19",
    ceo: "Aria Solis",
    website: "https://www.synapse-cloud.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "aiOperationsPlatform", value: 39, color: "#4d8cff" },
      { id: "dataPipelines", value: 34, color: "#22c37a" },
      { id: "securityGovernance", value: 27, color: "#ffb341" },
    ],
  },
  QNT: {
    legalName: "QuantForge Silicon",
    countryCode: "US",
    exchange: "NASDAQ",
    foundedYear: 2008,
    listedDate: "2016-11-03",
    ceo: "Evan Cole",
    website: "https://www.quantforge.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "aiAcceleratorSoc", value: 46, color: "#4d8cff" },
      { id: "packagingInterconnect", value: 32, color: "#22c37a" },
      { id: "designIpSoftware", value: 22, color: "#45c6ff" },
    ],
  },
  FAB: {
    legalName: "FabWorks Equipment",
    countryCode: "US",
    exchange: "NYSE",
    foundedYear: 1998,
    listedDate: "2012-05-24",
    ceo: "Daniel Keene",
    website: "https://www.fabworks.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "frontEndEquipment", value: 41, color: "#4d8cff" },
      { id: "backEndAutomation", value: 35, color: "#22c37a" },
      { id: "serviceParts", value: 24, color: "#ffb341" },
    ],
  },
  BIO: {
    legalName: "HelixBio Therapeutics",
    countryCode: "US",
    exchange: "NASDAQ",
    foundedYear: 2012,
    listedDate: "2020-02-21",
    ceo: "Dr. Lena Park",
    website: "https://www.helixbio.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "oncologyTherapeutics", value: 48, color: "#4d8cff" },
      { id: "immuneTherapeutics", value: 29, color: "#22c37a" },
      { id: "licensesRoyalties", value: 23, color: "#ff6f91" },
    ],
  },
  CRN: {
    legalName: "CuraNova Biologics",
    countryCode: "US",
    exchange: "NASDAQ",
    foundedYear: 2014,
    listedDate: "2021-07-09",
    ceo: "Jasper Noh",
    website: "https://www.curanova.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "rareDiseaseTherapeutics", value: 43, color: "#4d8cff" },
      { id: "inflammationTherapeutics", value: 33, color: "#22c37a" },
      { id: "cdmo", value: 24, color: "#ffb341" },
    ],
  },
  ENR: {
    legalName: "NovaEnergy Integrated",
    countryCode: "US",
    exchange: "NYSE",
    foundedYear: 1993,
    listedDate: "2006-03-30",
    ceo: "Rachel Boone",
    website: "https://www.novaenergy.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "lngGasDistribution", value: 38, color: "#4d8cff" },
      { id: "legacyPowerRefining", value: 34, color: "#ffb341" },
      { id: "renewablesStorage", value: 28, color: "#22c37a" },
    ],
  },
  OIL: {
    legalName: "TerraDrill Resources",
    countryCode: "US",
    exchange: "NYSE",
    foundedYear: 1987,
    listedDate: "2004-10-15",
    ceo: "Cole Mercer",
    website: "https://www.terradrill.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "oilGasProduction", value: 52, color: "#4d8cff" },
      { id: "oilfieldServices", value: 27, color: "#22c37a" },
      { id: "productionOptimization", value: 21, color: "#ffb341" },
    ],
  },
  RET: {
    legalName: "UrbanCart Commerce",
    countryCode: "US",
    exchange: "NYSE",
    foundedYear: 2005,
    listedDate: "2015-08-27",
    ceo: "Sophia Kim",
    website: "https://www.urbancart.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "storeSales", value: 47, color: "#4d8cff" },
      { id: "ecommerceLogistics", value: 31, color: "#22c37a" },
      { id: "adsMembership", value: 22, color: "#45c6ff" },
    ],
  },
  PAY: {
    legalName: "PayFlow Networks",
    countryCode: "US",
    exchange: "NASDAQ",
    foundedYear: 2009,
    listedDate: "2017-04-13",
    ceo: "Noah Bennett",
    website: "https://www.payflow.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "paymentProcessing", value: 42, color: "#4d8cff" },
      { id: "merchantSoftware", value: 30, color: "#22c37a" },
      { id: "merchantLending", value: 28, color: "#ffb341" },
    ],
  },
  MEM: {
    legalName: "MemeWorks Media",
    countryCode: "US",
    exchange: "NASDAQ",
    foundedYear: 2016,
    listedDate: "2022-01-20",
    ceo: "Troy Vega",
    website: "https://www.memeworks.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "communityCommerce", value: 36, color: "#4d8cff" },
      { id: "liveMedia", value: 34, color: "#ff6f91" },
      { id: "merchAds", value: 30, color: "#ffb341" },
    ],
  },
};

const SECTOR_FALLBACK = {
  AI: {
    countryCode: "US",
    exchange: "NASDAQ",
    foundedYear: 2010,
    listedDate: "2020-01-01",
    ceo: "Unknown",
    website: "https://www.company.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "platformRevenue", value: 40, color: "#4d8cff" },
      { id: "softwareRevenue", value: 33, color: "#22c37a" },
      { id: "servicesRevenue", value: 27, color: "#45c6ff" },
    ],
  },
  SEMI: {
    countryCode: "US",
    exchange: "NASDAQ",
    foundedYear: 2010,
    listedDate: "2020-01-01",
    ceo: "Unknown",
    website: "https://www.company.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "productsRevenue", value: 45, color: "#4d8cff" },
      { id: "servicesRevenue", value: 31, color: "#22c37a" },
      { id: "otherRevenue", value: 24, color: "#ffb341" },
    ],
  },
  BIO: {
    countryCode: "US",
    exchange: "NASDAQ",
    foundedYear: 2010,
    listedDate: "2020-01-01",
    ceo: "Unknown",
    website: "https://www.company.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "productsRevenue", value: 47, color: "#4d8cff" },
      { id: "licensesRevenue", value: 28, color: "#22c37a" },
      { id: "royaltiesRevenue", value: 25, color: "#ff6f91" },
    ],
  },
  ENR: {
    countryCode: "US",
    exchange: "NYSE",
    foundedYear: 2010,
    listedDate: "2020-01-01",
    ceo: "Unknown",
    website: "https://www.company.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "productionRevenue", value: 49, color: "#4d8cff" },
      { id: "distributionRevenue", value: 29, color: "#22c37a" },
      { id: "otherRevenue", value: 22, color: "#ffb341" },
    ],
  },
  CONS: {
    countryCode: "US",
    exchange: "NYSE",
    foundedYear: 2010,
    listedDate: "2020-01-01",
    ceo: "Unknown",
    website: "https://www.company.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "coreProducts", value: 46, color: "#4d8cff" },
      { id: "servicesRevenue", value: 32, color: "#22c37a" },
      { id: "adjacentIncome", value: 22, color: "#45c6ff" },
    ],
  },
  MEME: {
    countryCode: "US",
    exchange: "NASDAQ",
    foundedYear: 2010,
    listedDate: "2020-01-01",
    ceo: "Unknown",
    website: "https://www.company.example",
    revenueMixDate: "2025-12",
    revenueMix: [
      { id: "coreProducts", value: 39, color: "#4d8cff" },
      { id: "adsPlatform", value: 33, color: "#ff6f91" },
      { id: "otherRevenue", value: 28, color: "#ffb341" },
    ],
  },
};

export function getStockProfileBase(asset) {
  const exact = STOCK_PROFILE_BASES[asset?.symbol];
  if (exact) return exact;

  const fallback = SECTOR_FALLBACK[asset?.sector] || SECTOR_FALLBACK.CONS;
  return {
    legalName: asset?.name || asset?.symbol || "Unknown Company",
    ...fallback,
  };
}
